### ISSUE TITLE
Build Game Logic

### ISSUE THREAD

**Issue by UninspiredCarrot** [UninspiredCarrot/who-won#1]

**Comment by UninspiredCarrot** [comment]
# Building Game Logic
## Requirements
- [x] Register Players
- [x] Start a match with said players
- [ ] Decide who is serving
- [ ] Increase score of player
- [ ] End of Set logic
- [ ] Create a new set when needed
- [ ] Stop after 3 sets with winner and loser
- [ ] Retirement
- [ ] Undo
- [ ] Doubles serving logic ?

## Classes: 
- Player
  - Fields:  
    - id 
    - name 
    - handedness
  - Methods: 
    - switch handedness

- Match
  - Fields: 
    - player1 
    - player2 
    - sets 
    - player-serve 
    - player-side 
    - state: not started | playing | done
    - winner
    - loser
  - Methods: 
    - switch sides
    - get current set
    - new set
    - match done
   
- Set
  - Fields: 
    - points
    - state: not started | playing | done
  - Methods:
    - get point
    - increment
    - undo point
    - check if done
    
- Point
  - Fields: 
    - server 
    - winner 
    - path
    - state: tap | sequence
  - Methods: 
    - switch server
- Shot
  - Fields: 
    - x 
    - y
  - Methods:

**Comment by prasoonsingh** [comment]
Is this done only for singles or doubles as well ?

**Comment by prasoonsingh** [comment]
Is the score 21 or 15 or 11 configurable ? 
Is number of sets configurable?

**Comment by UninspiredCarrot** [comment]
single, 21x3
